// Top-level build file where you can add configuration options common to all sub-projects/modules.

plugins {
    id 'com.android.application' version '9.3.2' apply false
    id 'com.android.library' version '9.3.2' apply false
    id 'org.jetbrains.kotlin.android' version '2.2.10' apply false
    id 'org.jetbrains.kotlin.plugin.parcelize' version '2.2.10' apply false
}

ext.kotlin_version = '2.2.10'
ext.kotlinKspVersion = '2.2.10-2.0.2'

allprojects {
    repositories {
        mavenLocal()
        google()
        mavenCentral()
        maven { url "https://www.jitpack.io" }
    }
}

tasks.register('clean', Delete) {
    delete rootProject.layout.buildDirectory
}
