plugins {
    alias(libs.plugins.android.library)
    alias(libs.plugins.kotlin.android)
    alias(libs.plugins.kotlin.parcelize)
    alias(libs.plugins.ksp)
    id 'maven-publish'
}

android {
    compileSdk libs.versions.compileSdk.get().toInteger()

    defaultConfig {
        minSdkVersion libs.versions.minSdk.get().toInteger()
        targetSdkVersion libs.versions.targetSdk.get().toInteger()

        testInstrumentationRunner "androidx.test.runner.AndroidJUnitRunner"
        consumerProguardFiles 'consumer-rules.pro'
        vectorDrawables.useSupportLibrary = true
    }

    buildTypes {
        release {
            minifyEnabled false
            proguardFiles getDefaultProguardFile('proguard-android-optimize.txt'), 'proguard-rules.pro'
        }
    }
    compileOptions {
        sourceCompatibility JavaVersion.VERSION_21
        targetCompatibility JavaVersion.VERSION_21
    }
    kotlinOptions {
        jvmTarget = JavaVersion.VERSION_21.toString()
    }

    buildFeatures {
        viewBinding true
        buildConfig = true
    }

    namespace 'com.mediapicker.gallery'

    testOptions {
        unitTests {
            includeAndroidResources = true
        }
    }

    publishing {
        singleVariant('release') {
            withSourcesJar()
        }
    }
}

kotlin {
    jvmToolchain(JavaVersion.VERSION_21.toString().toInteger())
}

dependencies {
    implementation fileTree(dir: 'libs', include: ['*.jar'])
    implementation libs.kotlin.stdlib
    implementation libs.androidx.constraintlayout
    implementation libs.google.material
    implementation libs.androidx.lifecycle.extensions
    implementation libs.androidx.core.ktx
    implementation libs.chrisbanes.photoview
    testImplementation libs.junit
    testImplementation libs.robolectric
    androidTestImplementation libs.androidx.junit
    androidTestImplementation libs.androidx.espresso.core
    implementation libs.androidx.appcompat
    implementation libs.coil
    implementation libs.coil.gif
    implementation libs.coil.svg
    implementation libs.coil.network.okhttp
    implementation libs.permify
}

afterEvaluate {
    publishing {
        publications {
            release(MavenPublication) {
                from components.release

                groupId = 'com.github.IndiaOlx'
                artifactId = 'media-picker-android'
                version = '2.0.36'

                pom {
                    name = 'Media Picker Android'
                    description = 'Android library for picking media files'
                    url = 'https://github.com/IndiaOlx/media-picker-android'
                }
            }
        }
        repositories {
            mavenLocal()
        }
    }
}
